app/routes/auth.py
from flask import Blueprint, redirect, url_for, render_template, flash
from flask_login import current_user, login_user, logout_user

from app.models.user import User
from app.forms.auth import LoginForm, RegisterForm

auth = Blueprint('auth', __name__, url_prefix='/auth')


@auth.route('/')
@auth.route('/index')
def index():
    return redirect(url_for('auth.login'))


@auth.route('/login', methods=['GET', 'POST'])
def login():
    if current_user.is_authenticated:
        return redirect(url_for('main.index'))

    form = LoginForm()

    if form.validate_on_submit():
        user = User.query.filter_by(email=form.email.data).first()
        if user is not None and user.check_password(form.password.data):
            login_user(user, remember=form.remember_me.data)
            return redirect(url_for('main.index'))
        else:
            flash('Login Failed', 'danger')

    return render_template('views/auth/login.html', title='Login', form=form)


@auth.route('/register', methods=['GET', 'POST'])
def register():
    return "Ok\n"

    if current_user.is_authenticated:
        return redirect(url_for('main.index'))

    form = RegisterForm()

    if form.validate_on_submit():
        user = User()
        user.email = form.email.data
        user.name = form.name.data
        user.generate_password_hash(form.password.data)
        user.save()

        login_user(user)

        return redirect(url_for('main.index'))

    return render_template('views/auth/register.html', title='Register', form=form)


@auth.route('/logout')
def logout():
    logout_user()
    flash('Logged Out', 'success')
    return redirect(url_for('auth.login'))

app/routes/profile.py
from flask import Blueprint, render_template, flash
from flask_login import login_required, current_user

from app.models.user import User
from app.forms.profile import EditProfileForm, ChangePasswordForm

profile = Blueprint('profile', __name__, url_prefix='/profile')


@profile.route('/index', methods=['GET', 'POST'])
@login_required
def index():
    form = EditProfileForm()

    if form.validate_on_submit():
        user = User.query.filter_by(id=current_user.id).first()

        user.name = form.name.data
        user.email = form.email.data
        user.note = form.note.data
        user.save()

        flash('Profile Successfully Updated', 'success')

    form.name.data = current_user.name
    form.email.data = current_user.email
    form.note.data = current_user.note

    return render_template('views/profile/index.html', title='Edit Profile', form=form)


@profile.route('/password', methods=['GET', 'POST'])
@login_required
def password():
    form = ChangePasswordForm()

    if form.validate_on_submit():
        user = User.query.filter_by(id=current_user.id).first()

        user.generate_password_hash(form.new_password.data)
        user.save()

        flash('Password Successfully Updated', 'success')


    return render_template('views/profile/password.html', title='Edit Password', form=form)

app/templates/assets/base.html
{% from "macros/alerts.html" import error, alert %}

<!doctype html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="A Simple Structure For the Flask Framework">
    <meta name="author" content="Yunus Emre Geldegül">
    <link rel="icon" href="https://getbootstrap.com/docs/4.0/assets/img/favicons/favicon.ico">

    <title>
        {% if title is defined %}
            {{ title }} | Demongo
        {% else %}
            {{ site_name }}
        {% endif %}
    </title>

    <!-- Bootstrap core CSS -->
    <link href="https://getbootstrap.com/docs/4.0/dist/css/bootstrap.min.css" rel="stylesheet">

    <!-- Custom styles for this template -->
    <link href="https://getbootstrap.com/docs/4.0/examples/sticky-footer-navbar/sticky-footer-navbar.css"
          rel="stylesheet">

    {% block css %}

    {% endblock %}
</head>
<body>
<header>
    <!-- Fixed navbar -->
    <nav class="navbar navbar-expand-md navbar-dark fixed-top bg-dark">
        <a class="navbar-brand" href="{{ url_for('main.index') }}">Demongo</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarCollapse"
                aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapsefeature navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav mr-auto">
                {% if current_user.is_authenticated %}
                    <li class="nav-item">
                        <a class="nav-link" disabled href="">{{ current_user.name }}</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{{ url_for('profile.index') }}">Profile</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{{ url_for('profile.password') }}">Password</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{{ url_for('auth.logout') }}">Logout</a>
                    </li>
                {% else %}
                    <li class="nav-item">
                        <a class="nav-link" href="{{ url_for('auth.login') }}">Login</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{{ url_for('auth.register') }}">Register</a>
                    </li>
                {% endif %}
            </ul>
        </div>
    </nav>
</header>

<!-- Begin page content -->
{% block content %}

{% endblock %}

<footer class="footer">
    <div class="container">
        <span class="text-muted">Demongo, Yunus Emre Geldegül © 2020</span>
    </div>
</footer>

<script src="https://code.jquery.com/jquery-3.2.1.slim.min.js"></script>
<script>window.jQuery || document.write('<script src="view-source:https://getbootstrap.com/docs/4.0/assets/js/vendor/jquery-slim.min.js"><\/script>')</script>
<script src="https://getbootstrap.com/docs/4.0/assets/js/vendor/popper.min.js"></script>
<script src="https://getbootstrap.com/docs/4.0/dist/js/bootstrap.min.js"></script>

{% block js %}

{% endblock %}
</body>
</html>